export const config = {
  RETRY_EXPONENTIAL_MULTIPLIER: 500,
  MAX_REQUEST_RETRY: 3,
  SCRAPER_API_URL: process.env.SCRAPER_API_URL,
  USE_CSE_PAPI: !!process.env.USE_CSE_PAPI || true,
  TASK_FETCH_INTERVAL: +(process.env.TASK_FETCH_INTERVAL || 2000),
};
